Refactor v1
bradhackinen/nama pull request #12
Opened 2023-07-25 19:26 UTC by beny2000

- Restructured package files, and moved each model into its own file under the submodule `models`
- Renamed classes and adjusted imports as needed. Due to renaming model files with old class names will become invalid/unusable
- Clean up the demo notebook file

2023-07-31 14:37 UTC, bradhackinen requested changes
Hi Ben,

Thanks for this. Here is a list of things I'd like to change before we update the repo:

- Rename "Matcher" object to "MatchGroups" (and matcher.py to match_groups.py)
- Rename "ProjectorModel" to "EmbeddingModel"
- Drop ngrams, words, jaccard_similarity and cosine_similarity from utils.py (I don't think these are used anywhere other than token_similarity.py?)
- Move the loader functions to their class files (i.e., load_embeddings() should be in embeddings.py). I think this also includes moving from_df and read_csv to match_groups.py
- Move match_groups.py, scoring.py, and utils.py out of the "models" folder

Can also update the demo to match these changes?

Thanks!

-Brad

2023-08-02 19:48 UTC, bradhackinen requested changes
Hi Ben,

Thanks for updating the files. I still see some references to the term "matcher". Can you make sure these are all updated in the demos, code, comments, and docstrings? Please do the same for references to the "projector model"  as well.

Thanks!

2023-08-03 16:37 UTC, beny2000 commented
> Hi Ben,
> 
> Thanks for updating the files. I still see some references to the term "matcher". Can you make sure these are all updated in the demos, code, comments, and docstrings? Please do the same for references to the "projector model" as well.
> 
> Thanks!

What would you prefer the name for the new matcher be: `match_object`, `match_groups`, `match_groups_object`. I do think `matcher` is a simple name for this object though these option sound to clunky to me

2023-09-02 14:32 UTC, bradhackinen approved these changes

2023-09-02 14:32 UTC, merged